/**
 * Event Sourcing — Event Type Definitions
 *
 * These are the immutable facts that the system records.
 * Events live in Redis Streams first, then are replicated to PostgreSQL.
 *
 * Stream Keys:
 *   round:{roundId}:bets          → BetPlacedEvent records for a round
 *   global:settlement:{roundId}   → BetWonEvent / BetLostEvent / RoundClosedEvent
 */

export enum EventType {
  BET_PLACED   = 'BET_PLACED',
  BET_WON      = 'BET_WON',
  BET_LOST     = 'BET_LOST',
  ROUND_CLOSED = 'ROUND_CLOSED',
}

// ─────────────────────────────────────────────
// Base shape shared by every event
// ─────────────────────────────────────────────
export interface BaseEvent {
  /** UUID generated by the client on click — used for idempotency */
  eventId: string;
  type: EventType;
  /** Unix millisecond timestamp when the event was created */
  ts: number;
}

// ─────────────────────────────────────────────
// BET_PLACED
// Written to stream: round:{roundId}:bets
// ─────────────────────────────────────────────
export interface BetPlacedEvent extends BaseEvent {
  type: EventType.BET_PLACED;
  roundId: string;
  userId: string;
  /** BetType as string: SINGLE | PAIR | TRIPLE | QUAD */
  betType: string;
  /** Floor numbers selected by the user */
  numbers: number[];
  /** Per-number stake for SINGLE, total stake for others (Decimal string) */
  amount: string;
  /** Actual amount deducted from balance (amount * numbers.length for SINGLE) */
  totalDeducted: string;
  /** Balance before deduction (Decimal string) */
  balanceBefore: string;
  /** Balance after deduction (Decimal string) */
  balanceAfter: string;
}

// ─────────────────────────────────────────────
// BET_WON
// Written to stream: global:settlement:{roundId}
// ─────────────────────────────────────────────
export interface BetWonEvent extends BaseEvent {
  type: EventType.BET_WON;
  roundId: string;
  userId: string;
  /** The Prisma Bet.id that won (set after DB write; empty string during Redis phase) */
  betId: string;
  /** Payout amount credited to the user (Decimal string) */
  payout: string;
  multiplier: number;
  /** The winning floor numbers announced for this round */
  result: number[];
  betType: string;
  numbers: number[];
  /** Per-number stake for SINGLE */
  amount: string;
}

// ─────────────────────────────────────────────
// BET_LOST
// Written to stream: global:settlement:{roundId}
// ─────────────────────────────────────────────
export interface BetLostEvent extends BaseEvent {
  type: EventType.BET_LOST;
  roundId: string;
  userId: string;
  betId: string;
  result: number[];
  betType: string;
  numbers: number[];
  amount: string;
}

// ─────────────────────────────────────────────
// ROUND_CLOSED
// Written to stream: global:settlement:{roundId}
// One per round, written last during settlement
// ─────────────────────────────────────────────
export interface RoundClosedEvent extends BaseEvent {
  type: EventType.ROUND_CLOSED;
  roundId: string;
  result: number[];
  totalStake: string;
  totalPayout: string;
  houseProfit: string;
  totalBets: number;
  totalWinners: number;
}

// ─────────────────────────────────────────────
// Union type for type-safe event handling
// ─────────────────────────────────────────────
export type AnyGameEvent =
  | BetPlacedEvent
  | BetWonEvent
  | BetLostEvent
  | RoundClosedEvent;

// ─────────────────────────────────────────────
// Lua Script return codes
// ─────────────────────────────────────────────
export enum LuaBetResult {
  SUCCESS        =  1,
  INSUFFICIENT   = -1,
  DUPLICATE      = -2,
  ROUND_INACTIVE = -3,
}

// ─────────────────────────────────────────────
// Redis key helpers — centralised to prevent typos
// ─────────────────────────────────────────────
export const RedisKeys = {
  /** Live balance for a user */
  userBalance: (userId: string)       => `user:balance:${userId}`,
  /** Unix ms timestamp of last balance write — used for version checking */
  userBalanceVersion: (userId: string) => `user:balance:${userId}:version`,
  /** Redis Stream of BetPlacedEvents for a round */
  roundBetsStream: (roundId: string)  => `round:${roundId}:bets`,
  /** Redis Stream of settlement events for a round */
  settlementStream: (roundId: string) => `global:settlement:${roundId}`,
  /** Hash of floor → totalStaked for a round */
  roundExposure: (roundId: string)    => `round:${roundId}:exposure`,
  /** Current active round ID */
  activeRound: () => 'round:active',
  /** Idempotency guard: SET with TTL=300s */
  eventSeen: (eventId: string)        => `event:seen:${eventId}`,
  /** Settlement done flag — prevents double settlement */
  settlementDone: (roundId: string)   => `round:${roundId}:settled`,
};
