ALTER TABLE "GameRound" ADD COLUMN IF NOT EXISTS "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "GameRound" ADD COLUMN IF NOT EXISTS "openingResult" INTEGER[] DEFAULT '{}';
ALTER TABLE "GameRound" ADD COLUMN IF NOT EXISTS "openingType" VARCHAR(20) DEFAULT 'QUAD';
ALTER TABLE "GameRound" ADD COLUMN IF NOT EXISTS "status" VARCHAR(20) DEFAULT 'PENDING';
ALTER TABLE "GameRound" ADD COLUMN IF NOT EXISTS "totalStake" DOUBLE PRECISION DEFAULT 0;
ALTER TABLE "GameRound" ADD COLUMN IF NOT EXISTS "totalPayout" DOUBLE PRECISION DEFAULT 0;
ALTER TABLE "GameRound" ADD COLUMN IF NOT EXISTS "houseProfit" DOUBLE PRECISION DEFAULT 0;
